theme: jekyll-theme-cayman
title: Dimitris Polychronopoulos, Ph.D
tag_text: Dimitris Polychronopoulos
description: "The only true wisdom is in knowing you know nothing." ― Louisa May Alcott.

pages:
  markdown:
    extra: true
