theme: jekyll-theme-cayman
title: Dimitris Polychronopoulos, Ph.D
tag_text: Dimitris Polychronopoulos
description: “Ὁ βίος βραχύς, ἡ δὲ τέχνη μακρή, ὁ δὲ καιρὸς ὀξύς, ἡ δὲ πεῖρα σφαλερή, ἡ δὲ κρίσις χαλεπή.” ― HIPPOCRATES OF COS

pages:
  markdown:
    extra: true
