theme: jekyll-theme-cayman
title: Dimitris Polychronopoulos
tag_text: Dimitris Polychronopoulos
description: Welcome to my little corner on the web. This website is (still...) under development and contains work-related stuff. The idea / hope is to add fun / non-work related stuff in the future
