theme: jekyll-theme-cayman
title: Dimitris Polychronopoulos, Ph.D
tag_text: Dimitris Polychronopoulos
description: “Far away there in the sunshine are my highest aspirations. I may not reach them, but I can look up and see their beauty, believe in them, and try to follow where they lead.” ― Louisa May Alcott.

pages:
  markdown:
    extra: true
